# Generated by Django 5.0.14 on 2025-06-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_transport_shipment_albaran_shipment_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='wh_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
